# This file created by conda-build 25.1.2
# meta.yaml template originally from:
# /Users/ec2-user/tasks/task_176104870211490/packaging-feedstock/recipe, last modified Tue Oct 21 12:17:47 2025
# ------------------------------------------------

package:
  name: packaging
  version: '25.0'
source:
  sha256: d443872c98d677bf60f6a1f2f8c1cb748e8fe762d2bf9d3148b5599295b0fc4f
  url: https://pypi.io/packages/source/p/packaging/packaging-25.0.tar.gz
build:
  number: '1'
  script: /opt/miniconda3/conda-bld/packaging_1761049079023/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/bin/python
    -m pip install . --no-deps --no-build-isolation -vv
  string: py313hca03da5_1
requirements:
  host:
    - bzip2 1.0.8 h80987f9_6
    - ca-certificates 2025.9.9 hca03da5_0
    - expat 2.7.1 h313beb8_0
    - flit-core 3.12.0 py313hedbb292_0
    - libcxx 20.1.8 hd7fd590_1
    - libffi 3.4.4 hca03da5_1
    - libmpdec 4.0.0 h80987f9_0
    - libzlib 1.3.1 h5f15de7_0
    - ncurses 6.5 hee39554_0
    - openssl 3.0.18 h9b4081a_0
    - pip 25.2 pyhc872135_1
    - python 3.13.7 hc28b8d9_100_cp313
    - python_abi 3.13 1_cp313
    - readline 8.3 h0b18652_0
    - setuptools 80.9.0 py313hca03da5_0
    - sqlite 3.50.2 h79febb2_1
    - tk 8.6.15 hcd8a7d5_0
    - tzdata 2025b h04d1e81_0
    - wheel 0.45.1 py313hca03da5_0
    - xz 5.6.4 h80987f9_1
    - zlib 1.3.1 h5f15de7_0
  run:
    - python >=3.13,<3.14.0a0
    - python_abi 3.13.* *_cp313
test:
  commands:
    - pip check
    - pytest tests
  imports:
    - packaging
    - packaging._elffile
    - packaging._manylinux
    - packaging._musllinux
    - packaging._parser
    - packaging._structures
    - packaging.licenses._spdx
    - packaging.markers
    - packaging.metadata
    - packaging.requirements
    - packaging.specifiers
    - packaging.tags
    - packaging.utils
    - packaging.version
  requires:
    - pip
    - pretend
    - pytest >=6.2.0
  source_files:
    - tests
about:
  description: 'Reusable core utilities for various Python Packaging interoperability
    specifications.

    This library provides utilities that implement the interoperability specifications

    which have clearly one correct behaviour (eg: PEP 440) or benefit greatly from
    having

    a single shared implementation (eg: PEP 425).

    '
  dev_url: https://github.com/pypa/packaging
  doc_url: https://packaging.pypa.io
  home: https://github.com/pypa/packaging
  license: Apache-2.0 or BSD-2-Clause
  license_family: Apache
  license_file: LICENSE
  summary: Core utilities for Python packages
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - jakirkham
    - mingwandroid
    - nicoddemus
  skip-lints:
    - missing_wheel
