# This file created by conda-build 25.1.2
# ------------------------------------------------

package:
  name: cryptography
  version: 46.0.3
source:
  sha256: b40f9434d14affd208f03f4832aa616cb49e9ce414cb103825a8184eb94002f5
  url: https://github.com/pyca/cryptography/archive/refs/tags/46.0.3.tar.gz
build:
  noarch: false
  noarch_python: false
  number: '0'
  script: build_main.sh
  string: py313h81b0bee_0
requirements:
  build:
    - cctools 1021.4 h01d68c5_0
    - clang 20.1.8 h71b10da_0
    - clang-20 20.1.8 default_h988c893_0
    - clang_impl_osx-arm64 20.1.8 h05252e2_0
    - clang_osx-arm64 20.1.8 hf3c1794_0
    - clangxx 20.1.8 default_h0a00f0c_0
    - clangxx_impl_osx-arm64 20.1.8 he123483_0
    - clangxx_osx-arm64 20.1.8 hf3c1794_0
    - compiler-rt 20.1.8 hf790f37_0
    - compiler-rt_osx-arm64 20.1.8 hf790f37_0
    - icu 73.1 h313beb8_0
    - ld64 954.16 hbcf198d_0
    - libclang-cpp20.1 20.1.8 default_h988c893_0
    - libcxx 20.1.8 hd7fd590_1
    - libcxx-devel 20.1.8 he423718_1
    - libiconv 1.16 h80987f9_3
    - libllvm20 20.1.8 h1701f07_0
    - libxml2 2.13.9 h528a072_0
    - libzlib 1.3.1 h5f15de7_0
    - llvm-tools 20.1.8 hf790f37_0
    - llvm-tools-20 20.1.8 h1e49d39_0
    - lz4-c 1.9.4 h313beb8_1
    - macosx_deployment_target_osx-arm64 12.1 h3601aa6_2
    - rust 1.89.0 h0962b89_0
    - rust_osx-arm64 1.89.0 hc918bfe_2
    - tapi 1100.0.11 h8754e6a_1
    - tzdata 2025b h04d1e81_0
    - xz 5.6.4 h80987f9_1
    - zlib 1.3.1 h5f15de7_0
    - zstd 1.5.7 h817c040_0
  host:
    - bzip2 1.0.8 h80987f9_6
    - ca-certificates 2025.9.9 hca03da5_0
    - cffi 2.0.0 py313h73c2a22_1
    - expat 2.7.1 h313beb8_0
    - libcxx 20.1.8 hd7fd590_1
    - libffi 3.4.4 hca03da5_1
    - libmpdec 4.0.0 h80987f9_0
    - libzlib 1.3.1 h5f15de7_0
    - maturin 1.9.4 py313h8481970_0
    - ncurses 6.5 hee39554_0
    - openssl 3.0.18 h9b4081a_0
    - pip 25.2 pyhc872135_1
    - pycparser 2.23 py313hca03da5_0
    - python 3.13.9 hc7d8306_100_cp313
    - python_abi 3.13 1_cp313
    - readline 8.3 h0b18652_0
    - setuptools 80.9.0 py313hca03da5_0
    - sqlite 3.50.2 h79febb2_1
    - tk 8.6.15 hcd8a7d5_0
    - tzdata 2025b h04d1e81_0
    - wheel 0.45.1 py313hca03da5_0
    - xz 5.6.4 h80987f9_1
    - zlib 1.3.1 h5f15de7_0
  run:
    - __osx >=12.1
    - cffi>=2.0.0
    - openssl >=3.0.18,<4.0a0
    - python >=3.13,<3.14.0a0
    - python_abi 3.13.* *_cp313
  run_constrained:
    - bcrypt >=3.1.5
test:
  commands:
    - pip check
    - pytest -v tests
  imports:
    - cryptography
    - cryptography.fernet
    - cryptography.hazmat
    - cryptography.hazmat.backends
    - cryptography.hazmat.backends.openssl
    - cryptography.hazmat.bindings
    - cryptography.hazmat.bindings.openssl
    - cryptography.hazmat.primitives
    - cryptography.hazmat.primitives.asymmetric
    - cryptography.hazmat.primitives.ciphers
    - cryptography.hazmat.primitives.kdf
    - cryptography.hazmat.primitives.twofactor
    - cryptography.x509
  requires:
    - certifi >=2024
    - cryptography-vectors 46.0.3.*
    - pip
    - pretend >=0.7
    - pytest >=7.4.0
    - pytest-benchmark >=4.0
    - pytest-xdist >=3.5.0
  source_files:
    - pyproject.toml
    - tests
about:
  description: 'Cryptography is a package which provides cryptographic recipes and

    primitives to Python developers. Our goal is for it to be your

    "cryptographic standard library". It supports 3.8+ / PyPy 7.3.11+.

    cryptography includes both high level recipes and low level interfaces to

    common cryptographic algorithms such as symmetric ciphers, message digests,

    and key derivation functions.

    '
  dev_url: https://github.com/pyca/cryptography
  doc_url: https://cryptography.io
  home: https://github.com/pyca/cryptography
  license: Apache-2.0 OR BSD-3-Clause
  license_family: OTHER
  license_file:
    - LICENSE
    - LICENSE.APACHE
    - LICENSE.BSD
  summary: Provides cryptographic recipes and primitives to Python developers
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - chenghlee
    - jakirkham
    - ocefpaf
