# This file created by conda-build 25.1.2
# meta.yaml template originally from:
# /Users/ec2-user/tasks/task_176313474546386/certifi-feedstock/recipe, last modified Fri Nov 14 15:48:38 2025
# ------------------------------------------------

package:
  name: certifi
  version: 2025.11.12
source:
  - folder: certifi
    sha256: 3e67679bfbd220da166ee43339f498b605cfa0e836383f2e7b4da2d68364c0f2
    url: https://github.com/certifi/python-certifi/archive/refs/tags/2025.11.12.tar.gz
  - folder: pip_wheel
    sha256: 3790624780082365f47549d032f3770eeb2b1e8bd1f7b2e02dace1afa361b4ed
    url: https://pypi.org/packages/py3/p/pip/pip-24.3.1-py3-none-any.whl
  - folder: setuptools_wheel
    sha256: ce74b49e8f7110f9bf04883b730f4765b774ef3ef28f722cce7c273d253aaf7d
    url: https://pypi.org/packages/py3/s/setuptools/setuptools-75.6.0-py3-none-any.whl
build:
  number: '0'
  string: py313hca03da5_0
requirements:
  host:
    - bzip2 1.0.8 h80987f9_6
    - ca-certificates 2025.11.4 hca03da5_0
    - expat 2.7.3 h982b769_0
    - libcxx 20.1.8 hd7fd590_1
    - libffi 3.4.4 hca03da5_1
    - libmpdec 4.0.0 h80987f9_0
    - libzlib 1.3.1 h5f15de7_0
    - ncurses 6.5 hee39554_0
    - openssl 3.0.18 h9b4081a_0
    - python 3.13.9 hc7d8306_100_cp313
    - python_abi 3.13 1_cp313
    - readline 8.3 h0b18652_0
    - sqlite 3.51.0 hab6afd1_0
    - tk 8.6.15 hcd8a7d5_0
    - tzdata 2025b h04d1e81_0
    - xz 5.6.4 h80987f9_1
    - zlib 1.3.1 h5f15de7_0
  run:
    - python >=3.13,<3.14.0a0
    - python_abi 3.13.* *_cp313
test:
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('certifi')=='2025.11.12')"
    - pytest -vv certifi/certifi/tests
  imports:
    - certifi
  requires:
    - pip
    - pytest
  source_files:
    - certifi/certifi/tests
about:
  description: 'Certifi is a curated collection of Root Certificates for validating
    the

    trustworthiness of SSL certificates while verifying the identity of TLS

    hosts.

    '
  dev_url: https://github.com/certifi/python-certifi
  doc_url: https://github.com/certifi/python-certifi/blob/master/README.rst
  home: https://certifi.io
  license: MPL-2.0
  license_family: Other
  license_file: certifi/LICENSE
  summary: Python package for providing Mozilla's CA Bundle.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - jakirkham
    - mingwandroid
    - ocefpaf
    - pelson
    - sigmavirus24
  skip-lints:
    - missing_python_build_tool
