# This file created by conda-build 25.1.2
# ------------------------------------------------

package:
  name: anaconda-auth
  version: 0.12.3
source:
  sha256: 173007c0a5686b335e9d62f10d8a19e27b185a0d4c1dda76fbc92bf355fb69f2
  url: https://github.com/anaconda/anaconda-auth/archive/refs/tags/v0.12.3.tar.gz
build:
  entry_points:
    - conda-token = anaconda_auth._conda.conda_token:cli
  number: 0
  script:
    - python -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir
      -vv
    - python ./src/anaconda_auth/_conda/config.py --install
  string: py313hca03da5_0
requirements:
  host:
    - bzip2 1.0.8 h80987f9_6
    - ca-certificates 2025.12.2 hca03da5_0
    - hatch-vcs 0.5.0 py313hca03da5_0
    - hatchling 1.27.0 py313hca03da5_1
    - libcxx 20.1.8 hd7fd590_1
    - libexpat 2.7.3 h50f4ffc_4
    - libffi 3.4.4 hca03da5_1
    - libmpdec 4.0.0 h80987f9_0
    - libzlib 1.3.1 h5f15de7_0
    - ncurses 6.5 hee39554_0
    - openssl 3.0.18 h9b4081a_0
    - packaging 25.0 py313hca03da5_1
    - pathspec 0.12.1 py313hca03da5_1
    - pip 25.3 pyhc872135_0
    - pluggy 1.5.0 py313hca03da5_0
    - python 3.13.11 hc7d8306_100_cp313
    - python_abi 3.13 3_cp313
    - readline 8.3 h0b18652_0
    - setuptools 80.9.0 py313hca03da5_0
    - setuptools-scm 9.2.2 py313hca03da5_0
    - sqlite 3.51.0 hab6afd1_0
    - tk 8.6.15 hcd8a7d5_0
    - trove-classifiers 2025.5.9.12 py313hca03da5_0
    - tzdata 2025b h04d1e81_0
    - wheel 0.45.1 py313hca03da5_0
    - xz 5.6.4 h80987f9_1
    - zlib 1.3.1 h5f15de7_0
  run:
    - anaconda-cli-base >=0.7.0
    - cryptography >=3.4.0
    - keyring
    - pkce
    - pydantic
    - pyjwt
    - python >=3.13,<3.14.0a0
    - python-dotenv
    - python_abi 3.13.* *_cp313
    - requests
    - semver <4
  run_constrained:
    - anaconda-cloud-auth >=0.12.3
    - conda >=23.9.0
    - conda-token >=0.7.0
test:
  commands:
    - pip check
    - python -c "from anaconda_auth import __version__; assert __version__ == '0.12.3'"
    - python -m anaconda_auth._conda.config --verify
  imports:
    - anaconda_auth
  requires:
    - conda
    - pip
  source_files:
    - pyproject.toml
about:
  description: 'A client library for Anaconda.cloud APIs to authenticate and securely
    store API keys.

    This package also provides a requests client class that handles loading the API
    key

    for requests made to Anaconda Cloud services.

    '
  dev_url: https://github.com/anaconda/anaconda-auth
  doc_url: https://anaconda.github.io/anaconda-auth/
  home: https://anaconda.com
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A client auth library for Anaconda.cloud APIs
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - albertdefusco
    - mattkram
