# This file created by conda-build 25.1.2
# meta.yaml template originally from:
# /Users/ec2-user/tasks/task_176174493638757/annotated-types-feedstock/recipe, last modified Wed Oct 29 13:35:38 2025
# ------------------------------------------------

package:
  name: annotated-types
  version: 0.6.0
source:
  sha256: 563339e807e53ffd9c267e99fc6d9ea23eb8443c08f112651963e24e22f84a5d
  url: https://pypi.org/packages/source/a/annotated_types/annotated_types-0.6.0.tar.gz
build:
  number: '1'
  script: /opt/miniconda3/conda-bld/annotated-types_1761744949290/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/bin/python
    -m pip install . --no-deps --no-build-isolation -vv
  string: py313hca03da5_1
requirements:
  host:
    - bzip2 1.0.8 h80987f9_6
    - ca-certificates 2025.9.9 hca03da5_0
    - expat 2.7.1 h313beb8_0
    - hatchling 1.27.0 py313hca03da5_1
    - libcxx 20.1.8 hd7fd590_1
    - libffi 3.4.4 hca03da5_1
    - libmpdec 4.0.0 h80987f9_0
    - libzlib 1.3.1 h5f15de7_0
    - ncurses 6.5 hee39554_0
    - openssl 3.0.18 h9b4081a_0
    - packaging 25.0 py313hca03da5_1
    - pathspec 0.12.1 py313hca03da5_0
    - pip 25.2 pyhc872135_1
    - pluggy 1.5.0 py313hca03da5_0
    - python 3.13.9 hc7d8306_100_cp313
    - python_abi 3.13 1_cp313
    - readline 8.3 h0b18652_0
    - setuptools 80.9.0 py313hca03da5_0
    - sqlite 3.50.2 h79febb2_1
    - tk 8.6.15 hcd8a7d5_0
    - trove-classifiers 2025.5.9.12 py313hca03da5_0
    - tzdata 2025b h04d1e81_0
    - wheel 0.45.1 py313hca03da5_0
    - xz 5.6.4 h80987f9_1
    - zlib 1.3.1 h5f15de7_0
  run:
    - python >=3.13,<3.14.0a0
    - python_abi 3.13.* *_cp313
test:
  commands:
    - pip check
    - pytest -v tests
  imports:
    - annotated_types
  requires:
    - pip
    - pytest
  source_files:
    - tests
about:
  description: 'This package provides metadata objects which can be used to represent
    common constraints such as upper and lower

    bounds on scalar values and collection sizes, a Predicate marker for runtime checks,
    and descriptions of how we

    intend these metadata to be interpreted. In some cases, we also note alternative
    representations which do not

    require this package.

    '
  dev_url: https://github.com/annotated-types/annotated-types
  doc_url: https://github.com/annotated-types/annotated-types
  home: https://github.com/annotated-types/annotated-types
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Reusable constraint types to use with typing.Annotated
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - Zac-HD
    - mattwthompson
    - samuelcolvin
