# This file created by conda-build 25.1.2
# meta.yaml template originally from:
# /Users/ec2-user/tasks/task_176174482769005/charset-normalizer-feedstock/recipe, last modified Wed Oct 29 13:33:49 2025
# ------------------------------------------------

package:
  name: charset-normalizer
  version: 3.4.4
source:
  sha256: 94537985111c35f28720e43603b8e7b43a6ecfb2ce1d3058bbe955b73404e21a
  url: https://pypi.org/packages/source/c/charset-normalizer/charset_normalizer-3.4.4.tar.gz
build:
  entry_points:
    - normalizer = charset_normalizer.cli:cli_detect
  number: '0'
  script: /opt/miniconda3/conda-bld/charset-normalizer_1761744840553/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/bin/python
    -m pip install . --no-deps -vv --no-build-isolation
  string: py313hca03da5_0
requirements:
  host:
    - bzip2 1.0.8 h80987f9_6
    - ca-certificates 2025.9.9 hca03da5_0
    - expat 2.7.1 h313beb8_0
    - libcxx 20.1.8 hd7fd590_1
    - libffi 3.4.4 hca03da5_1
    - libmpdec 4.0.0 h80987f9_0
    - libzlib 1.3.1 h5f15de7_0
    - ncurses 6.5 hee39554_0
    - openssl 3.0.18 h9b4081a_0
    - pip 25.2 pyhc872135_1
    - python 3.13.9 hc7d8306_100_cp313
    - python_abi 3.13 1_cp313
    - readline 8.3 h0b18652_0
    - setuptools 80.9.0 py313hca03da5_0
    - sqlite 3.50.2 h79febb2_1
    - tk 8.6.15 hcd8a7d5_0
    - tzdata 2025b h04d1e81_0
    - wheel 0.45.1 py313hca03da5_0
    - xz 5.6.4 h80987f9_1
    - zlib 1.3.1 h5f15de7_0
  run:
    - python >=3.13,<3.14.0a0
    - python_abi 3.13.* *_cp313
test:
  commands:
    - pip check
    - normalizer --help
  imports:
    - charset_normalizer
  requires:
    - pip
about:
  description: 'A Library that helps you read text from unknown charset encoding.
    This project is motivated by chardet.

    '
  dev_url: https://github.com/jawah/charset_normalizer
  doc_url: https://charset-normalizer.readthedocs.io/
  home: https://github.com/jawah/charset_normalizer
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: The Real First Universal Charset Detector. Open, modern and actively maintained
    alternative to Chardet.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - ocefpaf
