# This file created by conda-build 25.1.2
# meta.yaml template originally from:
# /Users/ec2-user/tasks/task_176190300670094/semver-feedstock/recipe, last modified Fri Oct 31 09:30:15 2025
# ------------------------------------------------

package:
  name: semver
  version: 3.0.4
source:
  sha256: afc7d8c584a5ed0a11033af086e8af226a9c0b206f313e0301f8dd7b6b589602
  url: https://pypi.org/packages/source/s/semver/semver-3.0.4.tar.gz
build:
  entry_points:
    - pysemver = semver.cli:main
  number: '0'
  script: /opt/miniconda3/conda-bld/semver_1761903026306/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/bin/python
    -m pip install . -vv --no-deps --no-build-isolation
  string: py313hca03da5_0
requirements:
  host:
    - bzip2 1.0.8 h80987f9_6
    - ca-certificates 2025.9.9 hca03da5_0
    - expat 2.7.1 h313beb8_0
    - libcxx 20.1.8 hd7fd590_1
    - libffi 3.4.4 hca03da5_1
    - libmpdec 4.0.0 h80987f9_0
    - libzlib 1.3.1 h5f15de7_0
    - ncurses 6.5 hee39554_0
    - openssl 3.0.18 h9b4081a_0
    - pip 25.2 pyhc872135_1
    - python 3.13.9 hc7d8306_100_cp313
    - python_abi 3.13 1_cp313
    - readline 8.3 h0b18652_0
    - setuptools 80.9.0 py313hca03da5_0
    - sqlite 3.50.2 h79febb2_1
    - tk 8.6.15 hcd8a7d5_0
    - tzdata 2025b h04d1e81_0
    - wheel 0.45.1 py313hca03da5_0
    - xz 5.6.4 h80987f9_1
    - zlib 1.3.1 h5f15de7_0
  run:
    - python >=3.13,<3.14.0a0
    - python_abi 3.13.* *_cp313
test:
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('semver')=='3.0.4')"
    - pytest -v tests
    - pysemver -h
  imports:
    - semver
  requires:
    - pip
    - pytest
  source_files:
    - tests
about:
  description: 'A Python module for semantic versioning. Simplifies comparing versions.

    '
  dev_url: https://github.com/python-semver/python-semver
  doc_url: https://github.com/python-semver/python-semver
  home: https://github.com/python-semver/python-semver
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Python package to work with Semantic Versioning
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - carlodri
    - rmax
