# This file created by conda-build 25.1.2
# ------------------------------------------------

package:
  name: typer
  version: 0.20.0
source:
  - folder: typer-slim
    sha256: 9fc6607b3c6c20f5c33ea9590cbeb17848667c51feee27d9e314a579ab07d1a3
    url: https://pypi.org/packages/source/t/typer-slim/typer_slim-0.20.0.tar.gz
  - folder: typer-cli
    sha256: af928da59aed5770f50e4c0f135f70ebf798d5bd00586d86d4c3015a5718a021
    url: https://pypi.org/packages/source/t/typer-cli/typer_cli-0.20.0.tar.gz
  - folder: typer
    sha256: 1aaf6494031793e4876fb0bacfa6a912b551cf43c1e63c800df8b1a866720c37
    url: https://pypi.org/packages/source/t/typer/typer-0.20.0.tar.gz
build:
  entry_points:
    - typer = typer.cli:main
  number: 0
  string: py313hca03da5_0
requirements:
  host:
    - bzip2 1.0.8 h80987f9_6
    - ca-certificates 2025.12.2 hca03da5_0
    - libcxx 20.1.8 hd7fd590_1
    - libexpat 2.7.3 h50f4ffc_4
    - libffi 3.4.4 hca03da5_1
    - libmpdec 4.0.0 h80987f9_0
    - libzlib 1.3.1 h5f15de7_0
    - ncurses 6.5 hee39554_0
    - openssl 3.0.18 h9b4081a_0
    - packaging 25.0 py313hca03da5_1
    - pdm-backend 2.4.6 py313hca03da5_0
    - pip 25.3 pyhc872135_0
    - pyproject_hooks 1.2.0 py313hca03da5_1
    - python 3.13.11 hc7d8306_100_cp313
    - python-build 1.3.0 py313hca03da5_1
    - python_abi 3.13 3_cp313
    - readline 8.3 h0b18652_0
    - setuptools 80.9.0 py313hca03da5_0
    - sqlite 3.51.0 hab6afd1_0
    - tk 8.6.15 hcd8a7d5_0
    - tzdata 2025b h04d1e81_0
    - wheel 0.45.1 py313hca03da5_0
    - xz 5.6.4 h80987f9_1
    - zlib 1.3.1 h5f15de7_0
  run:
    - python >=3.13,<3.14.0a0
    - python_abi 3.13.* *_cp313
    - typer-slim-standard 0.20.0 py313hca03da5_0
test:
  commands:
    - pip check
    - typer --version
    - typer --help
    - cd typer && coverage run --source=typer --branch -m pytest -vv --color=yes --tb=long
      -k "not ((multiple_values and main) or completion or invalid_score)"
  imports:
    - typer
  requires:
    - coverage
    - pip
    - pytest
  source_files:
    - typer/docs_src
    - typer/tests
about:
  description: 'Typer is library for building CLI applications that users will love
    using and developers will love creating. Based on Python 3.6+ type hints.


    The key features are:


    Intuitive to write: Great editor support. Completion everywhere. Less time debugging.
    Designed to be easy to use and learn. Less time reading docs.

    Easy to use: It''s easy to use for the final users. Automatic help, and automatic
    completion for all shells.

    Short: Minimize code duplication. Multiple features from each parameter declaration.
    Fewer bugs.

    Start simple: The simplest example adds only 2 lines of code to your app: 1 import,
    1 function call.

    Grow large: Grow in complexity as much as you want, create arbitrarily complex
    trees of commands and groups of subcommands, with options and arguments.

    '
  dev_url: https://github.com/tiangolo/typer
  doc_url: https://typer.tiangolo.com
  home: https://github.com/tiangolo/typer
  license: MIT
  license_family: MIT
  license_file: typer/LICENSE
  summary: A library for building CLI applications
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - bollwyvl
    - dfornika
