# This file created by conda-build 25.1.2
# meta.yaml template originally from:
# /Users/ec2-user/tasks/task_176236135574494/conda-package-streaming-feedstock/recipe, last modified Wed Nov  5 16:53:40 2025
# ------------------------------------------------

package:
  name: conda-package-streaming
  version: 0.12.0
source:
  sha256: 2cd261d3bc3bd4c51e2bb84a8397b6cc1b591f837838439d4befc12fc3d77314
  url: https://github.com/conda/conda-package-streaming/archive/refs/tags/v0.12.0.tar.gz
build:
  number: '1'
  script: /opt/miniconda3/conda-bld/conda-package-streaming_1762361629849/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin/python
    -m pip install --no-deps --no-build-isolation . -vv
  string: py313hca03da5_1
requirements:
  host:
    - bzip2 1.0.8 h80987f9_6
    - ca-certificates 2025.11.4 hca03da5_0
    - expat 2.7.3 h982b769_0
    - flit-core 3.12.0 py313hedbb292_0
    - libcxx 20.1.8 hd7fd590_1
    - libffi 3.4.4 hca03da5_1
    - libmpdec 4.0.0 h80987f9_0
    - libzlib 1.3.1 h5f15de7_0
    - ncurses 6.5 hee39554_0
    - openssl 3.0.18 h9b4081a_0
    - pip 25.2 pyhc872135_1
    - python 3.13.9 hc7d8306_100_cp313
    - python_abi 3.13 1_cp313
    - readline 8.3 h0b18652_0
    - setuptools 80.9.0 py313hca03da5_0
    - sqlite 3.50.2 h79febb2_1
    - tk 8.6.15 hcd8a7d5_0
    - tzdata 2025b h04d1e81_0
    - wheel 0.45.1 py313hca03da5_0
    - xz 5.6.4 h80987f9_1
    - zlib 1.3.1 h5f15de7_0
  run:
    - python >=3.13,<3.14.0a0
    - python_abi 3.13.* *_cp313
    - requests
    - zstandard >=0.15
test:
  commands:
    - pip check
  imports:
    - conda_package_streaming
    - conda_package_streaming.url
  requires:
    - pip
about:
  description: 'An efficient library to read from new and old format .conda and .tar.bz2
    conda packages.

    '
  dev_url: https://github.com/conda/conda-package-streaming
  doc_url: https://conda.github.io/conda-package-streaming/
  home: https://github.com/conda/conda-package-streaming
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: An efficient library to read from new and old format .conda and .tar.bz2
    conda packages.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - dholth
