# This file created by conda-build 25.1.2
# meta.yaml template originally from:
# /Users/ec2-user/tasks/task_176400977334475/pydantic-core-feedstock/recipe, last modified Mon Nov 24 18:42:55 2025
# ------------------------------------------------

package:
  name: pydantic-core
  version: 2.41.5
source:
  sha256: 08daa51ea16ad373ffd5e7606252cc32f07bc72b28284b6bc9c6df804816476e
  url: https://pypi.org/packages/source/p/pydantic-core/pydantic_core-2.41.5.tar.gz
build:
  number: '1'
  script:
    - /opt/miniconda3/conda-bld/pydantic-core_1764009784214/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin/python
      -m pip install . -vv --no-deps --no-build-isolation
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
  string: py313h931abed_1
requirements:
  build:
    - cargo-bundle-licenses 0.5.0 ha6e5c4f_0
    - cctools 1021.4 h01d68c5_0
    - clang 20.1.8 h71b10da_0
    - clang-20 20.1.8 default_h988c893_0
    - clang_impl_osx-arm64 20.1.8 h05252e2_0
    - clang_osx-arm64 20.1.8 hf3c1794_0
    - clangxx 20.1.8 default_h0a00f0c_0
    - clangxx_impl_osx-arm64 20.1.8 he123483_0
    - clangxx_osx-arm64 20.1.8 hf3c1794_0
    - compiler-rt 20.1.8 hf790f37_0
    - compiler-rt_osx-arm64 20.1.8 hf790f37_0
    - icu 73.1 h313beb8_0
    - ld64 954.16 hbcf198d_0
    - libclang-cpp20.1 20.1.8 default_h988c893_0
    - libcxx 20.1.8 hd7fd590_1
    - libcxx-devel 20.1.8 he423718_1
    - libiconv 1.16 h80987f9_3
    - libllvm20 20.1.8 h1701f07_0
    - libxml2 2.13.9 h528a072_0
    - libzlib 1.3.1 h5f15de7_0
    - llvm-tools 20.1.8 hf790f37_0
    - llvm-tools-20 20.1.8 h1e49d39_0
    - lz4-c 1.9.4 h313beb8_1
    - macosx_deployment_target_osx-arm64 12.1 h3601aa6_2
    - rust 1.89.0 h0962b89_0
    - rust_osx-arm64 1.89.0 hc918bfe_2
    - tapi 1100.0.11 h8754e6a_1
    - tzdata 2025b h04d1e81_0
    - xz 5.6.4 h80987f9_1
    - zlib 1.3.1 h5f15de7_0
    - zstd 1.5.7 h817c040_0
  host:
    - bzip2 1.0.8 h80987f9_6
    - ca-certificates 2025.11.4 hca03da5_0
    - expat 2.7.3 h982b769_0
    - libcxx 20.1.8 hd7fd590_1
    - libffi 3.4.4 hca03da5_1
    - libmpdec 4.0.0 h80987f9_0
    - libzlib 1.3.1 h5f15de7_0
    - maturin 1.9.4 py313h8481970_0
    - ncurses 6.5 hee39554_0
    - openssl 3.0.18 h9b4081a_0
    - pip 25.3 pyhc872135_0
    - python 3.13.9 hc7d8306_100_cp313
    - python_abi 3.13 1_cp313
    - readline 8.3 h0b18652_0
    - setuptools 80.9.0 py313hca03da5_0
    - sqlite 3.51.0 hab6afd1_0
    - tk 8.6.15 hcd8a7d5_0
    - tzdata 2025b h04d1e81_0
    - wheel 0.45.1 py313hca03da5_0
    - xz 5.6.4 h80987f9_1
    - zlib 1.3.1 h5f15de7_0
  run:
    - __osx >=12.1
    - python >=3.13,<3.14.0a0
    - python_abi 3.13.* *_cp313
    - typing-extensions >=4.14.1
test:
  commands:
    - pip check
    - python -c "from pydantic_core import PydanticUndefinedType"
    - pytest -v --ignore=tests/test_docstrings.py --ignore=tests/test_hypothesis.py
      --ignore=tests/validators/test_allow_partial.py --ignore=tests/validators/test_frozenset.py
      --ignore=tests/validators/test_list.py --ignore=tests/validators/test_set.py
  imports:
    - pydantic_core
  requires:
    - dirty-equals
    - hypothesis
    - pip
    - pytest
    - pytest-benchmark
    - pytest-mock
    - pytest-timeout
    - typing-inspection
  source_files:
    - pyproject.toml
    - tests
about:
  description: 'This package provides the core functionality for pydantic validation
    and serialization.

    '
  dev_url: https://github.com/pydantic/pydantic-core
  doc_url: https://docs.pydantic.dev
  home: https://github.com/pydantic/pydantic-core
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Core validation logic for pydantic written in rust
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - adriangb
    - dmontagu
    - pavelzw
    - samuelcolvin
    - xhochy
