# This file created by conda-build 25.1.2
# meta.yaml template originally from:
# /Users/ec2-user/tasks/task_176496035721330/brotlicffi-feedstock/recipe, last modified Fri Dec  5 18:59:10 2025
# ------------------------------------------------

package:
  name: brotlicffi
  version: 1.2.0.0
source:
  sha256: 34345d8d1f9d534fcac2249e57a4c3c8801a33c9942ff9f8574f67a175e17adb
  url: https://pypi.org/packages/source/b/brotlicffi/brotlicffi-1.2.0.0.tar.gz
build:
  number: '0'
  script: /opt/miniconda3/conda-bld/brotlicffi_1764961161081/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/bin/python
    -m pip install . --no-deps --no-build-isolation -vv
  string: py313h50f4ffc_0
requirements:
  build:
    - cctools 1021.4 h01d68c5_0
    - clang 20.1.8 h71b10da_0
    - clang-20 20.1.8 default_h988c893_0
    - clang_impl_osx-arm64 20.1.8 h05252e2_0
    - clang_osx-arm64 20.1.8 hf3c1794_0
    - clangxx 20.1.8 default_h0a00f0c_0
    - clangxx_impl_osx-arm64 20.1.8 he123483_0
    - clangxx_osx-arm64 20.1.8 hf3c1794_0
    - compiler-rt 20.1.8 hf790f37_0
    - compiler-rt_osx-arm64 20.1.8 hf790f37_0
    - icu 73.1 h313beb8_0
    - ld64 954.16 hbcf198d_0
    - libclang-cpp20.1 20.1.8 default_h988c893_0
    - libcxx 20.1.8 hd7fd590_1
    - libcxx-devel 20.1.8 he423718_1
    - libiconv 1.16 h80987f9_3
    - libllvm20 20.1.8 h1701f07_0
    - libxml2 2.13.9 h528a072_0
    - libzlib 1.3.1 h5f15de7_0
    - llvm-tools 20.1.8 hf790f37_0
    - llvm-tools-20 20.1.8 h1e49d39_0
    - lz4-c 1.9.4 h313beb8_1
    - macosx_deployment_target_osx-arm64 12.1 h3601aa6_2
    - tapi 1100.0.11 h8754e6a_1
    - tzdata 2025b h04d1e81_0
    - xz 5.6.4 h80987f9_1
    - zlib 1.3.1 h5f15de7_0
    - zstd 1.5.7 h817c040_0
  host:
    - bzip2 1.0.8 h80987f9_6
    - ca-certificates 2025.12.2 hca03da5_0
    - cffi 2.0.0 py313h73c2a22_1
    - expat 2.7.3 h50f4ffc_1
    - libcxx 20.1.8 hd7fd590_1
    - libexpat 2.7.3 h50f4ffc_1
    - libffi 3.4.4 hca03da5_1
    - libmpdec 4.0.0 h80987f9_0
    - libzlib 1.3.1 h5f15de7_0
    - ncurses 6.5 hee39554_0
    - openssl 3.0.18 h9b4081a_0
    - pip 25.3 pyhc872135_0
    - pycparser 2.23 py313hca03da5_0
    - python 3.13.10 hc7d8306_100_cp313
    - python_abi 3.13 3_cp313
    - readline 8.3 h0b18652_0
    - setuptools 80.9.0 py313hca03da5_0
    - sqlite 3.51.0 hab6afd1_0
    - tk 8.6.15 hcd8a7d5_0
    - tzdata 2025b h04d1e81_0
    - wheel 0.45.1 py313hca03da5_0
    - xz 5.6.4 h80987f9_1
    - zlib 1.3.1 h5f15de7_0
  run:
    - __osx >=12.1
    - cffi >=1.17.0
    - libcxx >=20
    - python >=3.13,<3.14.0a0
    - python_abi 3.13.* *_cp313
test:
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('brotlicffi')=='1.2.0.0')"
  imports:
    - brotlicffi
  requires:
    - pip
  source_files:
    - test
about:
  description: Python CFFI bindings to the Brotli library
  dev_url: https://github.com/python-hyper/brotlicffi
  doc_url: https://github.com/python-hyper/brotlicffi/blob/main/README.rst
  home: https://github.com/python-hyper/brotlicffi
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python CFFI bindings to the Brotli library
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - katietz
    - sarthakpati
    - sethmlarson
  skip-lints:
    - host_section_needs_exact_pinnings
