# This file created by conda-build 24.9.0
# meta.yaml template originally from:
# /var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/abs_67kp39sonk/clone/recipe, last modified Wed Aug 13 06:44:59 2025
# ------------------------------------------------

package:
  name: libunistring
  version: '1.3'
source:
  fn: libunistring-1.3.tar.xz
  sha256: f245786c831d25150f3dfb4317cda1acc5e3f79a5da4ad073ddca58886569527
  url: https://ftpmirror.gnu.org/libunistring/libunistring-1.3.tar.xz
build:
  number: '0'
  run_exports:
    - libunistring >=1,<2.0a0
  string: h1799b2a_0
requirements:
  build:
    - cctools_osx-arm64 949.0.1 h69e4071_26
    - clang 14.0.6 hca03da5_2
    - clang-14 14.0.6 default_h1b80db6_2
    - clang_osx-arm64 14.0.6 h9ff6fda_0
    - clangxx 14.0.6 default_h1b80db6_2
    - compiler-rt 14.0.6 h4ccfd99_0
    - compiler-rt_osx-arm64 14.0.6 h4fb70ea_0
    - ld64_osx-arm64 530 hac4b543_26
    - ldid 2.1.5 h20b2a84_3
    - libclang-cpp14 14.0.6 default_h1b80db6_2
    - libcxx 14.0.6 h848a8c0_0
    - libffi 3.4.4 hca03da5_1
    - libllvm14 14.0.6 h19fdd8a_4
    - libtool 2.4.7 h313beb8_0
    - llvm-tools 14.0.6 h7ec7a93_4
    - macosx_deployment_target_osx-arm64 11.1 had524d6_1
    - make 4.3 h620ffc9_1
    - tapi 1100.0.11 h8754e6a_1
    - zlib 1.2.13 h18a0788_1
  host:
    - __osx >=11.1
  run:
    - __osx >=11.1
test:
  commands:
    - test -e $PREFIX/lib/libunistring${SHLIB_EXT}
about:
  description: 'This library provides functions for manipulating Unicode strings and

    for manipulating C strings according to the Unicode standard.

    '
  dev_url: https://git.savannah.gnu.org/gitweb/?p=libunistring.git
  doc_url: https://www.gnu.org/software/libunistring/manual/libunistring.html
  home: https://www.gnu.org/software/libunistring
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: COPYING
  summary: C unicode string manipulation library
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 671b4cbd-3905-485a-a190-26922d37e114
  recipe-maintainers:
    - bgruening
    - chenghlee
    - stefan-balke
  remote_url: git@github.com:AnacondaRecipes/libunistring-feedstock.git
  sha: 8e6f0f0b878447f309b22c664ea53b916e3a2334
