# This file created by conda-build 25.1.2
# ------------------------------------------------

package:
  name: python
  version: 3.12.12
source:
  - patches:
      - patches/0000-branding.patch
      - patches/0001-Win32-Change-FD_SETSIZE-from-512-to-2048.patch
      - patches/0002-Win32-Do-not-download-externals.patch
      - patches/0003-Fix-find_library-so-that-it-looks-in-sys.prefix-lib-.patch
      - patches/0004-Disable-registry-lookup-unless-CONDA_PY_ALLOW_REG_PA.patch
      - patches/0005-Unvendor-openssl.patch
      - patches/0006-Unvendor-sqlite3.patch
      - patches/0007-Add-CondaEcosystemModifyDllSearchPath.patch
      - patches/0008-Doing-d1trimfile.patch
      - patches/0009-cross-compile-darwin.patch
      - patches/0010-Fix-TZPATH-on-windows.patch
      - patches/0011-Make-dyld-search-work-with-SYSTEM_VERSION_COMPAT-1.patch
      - patches/0012-Unvendor-bzip2.patch
      - patches/0013-Unvendor-libffi.patch
      - patches/0014-Unvendor-tcltk.patch
      - patches/0015-unvendor-xz.patch
      - patches/0016-unvendor-zlib.patch
      - patches/0017-Do-not-pass-g-to-GCC-when-not-Py_DEBUG.patch
      - patches/0018-Unvendor-expat.patch
      - patches/0019-Remove-unused-readelf.patch
      - patches/0021-Override-configure-LIBFFI.patch
      - patches/0022-Allow-linking-ncursesw-panelw-on-macOS-if-available.patch
      - patches/0023-Do-not-define-pid_t-as-it-might-conflict-with-the-ac.patch
    sha256: fb85a13414b028c49ba18bbd523c2d055a30b56b18b92ce454ea2c51edc656c4
    url: https://www.python.org/ftp/python/3.12.12/Python-3.12.12.tar.xz
build:
  activate_in_script: true
  detect_binary_files_with_prefix: true
  ignore_run_exports_from:
    - clangxx_osx-arm64 20.*
  no_link: null
  number: 1
  script_env:
    - CONDA_FORGE=no
    - PY_INTERP_DEBUG=no
    - PY_INTERP_LINKAGE_NATURE=static
  string: h2bfc596_1
requirements:
  build:
    - cctools 1021.4 h01d68c5_0
    - clang 20.1.8 h71b10da_0
    - clang-20 20.1.8 default_h988c893_0
    - clang_impl_osx-arm64 20.1.8 h05252e2_0
    - clang_osx-arm64 20.1.8 hf3c1794_0
    - clangxx 20.1.8 default_h0a00f0c_0
    - clangxx_impl_osx-arm64 20.1.8 he123483_0
    - clangxx_osx-arm64 20.1.8 hf3c1794_0
    - compiler-rt 20.1.8 hf790f37_0
    - compiler-rt_osx-arm64 20.1.8 hf790f37_0
    - gettext 0.21.0 hbdbcc25_2
    - icu 73.1 h313beb8_0
    - ld64 954.16 hbcf198d_0
    - libclang-cpp20.1 20.1.8 default_h988c893_0
    - libcxx 20.1.8 hd7fd590_1
    - libcxx-devel 20.1.8 he423718_1
    - libiconv 1.16 h80987f9_3
    - libllvm20 20.1.8 h1701f07_0
    - libtool 2.4.7 h313beb8_0
    - libxml2 2.13.8 h0b34f26_0
    - libzlib 1.3.1 h5f15de7_0
    - llvm-openmp 20.1.8 he822017_0
    - llvm-tools 20.1.8 hf790f37_0
    - llvm-tools-20 20.1.8 h1e49d39_0
    - lz4-c 1.9.4 h313beb8_1
    - make 4.3 h620ffc9_1
    - ncurses 6.5 hee39554_0
    - pkg-config 0.29.2 h1a28f6b_0
    - sed 4.9 h79febb2_0
    - tapi 1100.0.11 h8754e6a_1
    - tzdata 2025b h04d1e81_0
    - xz 5.6.4 h80987f9_1
    - zlib 1.3.1 h5f15de7_0
    - zstd 1.5.7 h817c040_0
  host:
    - bzip2 1.0.8 h80987f9_6
    - ca-certificates 2025.9.9 hca03da5_0
    - expat 2.7.1 h313beb8_0
    - libcxx 20.1.8 hd7fd590_1
    - libffi 3.4.4 hca03da5_1
    - ncurses 6.4 h313beb8_0
    - openssl 3.0.18 h9b4081a_0
    - readline 8.2 h1a28f6b_0
    - sqlite 3.50.2 h79febb2_1
    - tk 8.6.15 hcd8a7d5_0
    - xz 5.6.4 h80987f9_1
    - zlib 1.2.13 ha1e9f54_2
  run:
    - bzip2 >=1.0.8,<2.0a0
    - expat >=2.7.1,<3.0a0
    - libffi >=3.4,<4.0a0
    - ncurses >=6.4,<7.0a0
    - openssl >=3.0.18,<4.0a0
    - readline >=8.2,<9.0a0
    - sqlite >=3.50.2,<4.0a0
    - tk >=8.6.15,<8.7.0a0
    - tzdata
    - xz >=5.6.4,<6.0a0
    - zlib >=1.2.13,<2.0a0
  run_constrained:
    - python_abi 3.12.* *_cp312
test:
  commands:
    - python -V
    - python3 -V
    - 2to3 -h
    - pydoc -h
    - python3-config --help
    - python -c "from zoneinfo import ZoneInfo; from datetime import datetime; dt
      = datetime(2020, 10, 31, 12, tzinfo=ZoneInfo('America/Los_Angeles')); print(dt.tzname())"
    - python -m venv test-venv
    - test-venv/bin/python -c "import ctypes"
    - python -c "import sysconfig; print(sysconfig.get_config_var('CC'))"
    - for f in ${CONDA_PREFIX}/lib/python*/_sysconfig*.py; do echo "Checking $f:";
      if [[ `rg @[^@]*@ $f` ]]; then echo "FAILED ON $f"; cat $f; exit 1; fi; done
    - test ! -f ${PREFIX}/lib/libpython${PKG_VERSION%.*}.a
    - test ! -f ${PREFIX}/lib/libpython${PKG_VERSION%.*}.nolto.a
    - pushd tests
    - pushd prefix-replacement
    - bash build-and-test.sh
    - popd
    - pushd cmake
    - cmake -GNinja -DPY_VER=3.12.12
    - popd
    - popd
    - python run_test.py
    - test ! -f default.profraw
    - test -d "$PREFIX/lib/python3.1/site-packages"
    - python3.1 --version
    - python -c "from ctypes import CFUNCTYPE; CFUNCTYPE(None)(id)"
    - TERM=xterm >/dev/null python -c "import curses; scr = curses.initscr(); curses.unget_wch('x');
      assert 'x' ==  scr.get_wch()"
  files:
    - run_test.py
    - tests/cmake/*
    - tests/cython/*
    - tests/prefix-replacement/*
  requires:
    - clang_osx-arm64 20.*
    - clangxx_osx-arm64 20.*
    - cmake-no-system
    - make
    - ninja-base
    - ripgrep
about:
  description: 'Python is a widely used high-level, general-purpose, interpreted,
    dynamic

    programming language. Its design philosophy emphasizes code

    readability, and its syntax allows programmers to express concepts in

    fewer lines of code than would be possible in languages such as C++ or

    Java. The language provides constructs intended to enable clear programs

    on both a small and large scale.

    '
  dev_url: https://devguide.python.org/
  doc_url: https://www.python.org/doc/versions/
  home: https://www.python.org/
  license: PSF-2.0
  license_family: PSF
  license_file: LICENSE
  license_url: https://docs.python.org/3/license.html
  summary: General purpose programming language
extra:
  copy_test_source_files: true
  feedstock-name: python
  final: true
  recipe-maintainers:
    - isuruf
    - jakirkham
    - katietz
    - mbargull
    - mingwandroid
    - msarahan
    - ocefpaf
    - pelson
    - scopatz
    - xhochy
  skip-lints:
    - license_file_overspecified
