# This file created by conda-build 25.1.2
# meta.yaml template originally from:
# /Users/ec2-user/tasks/task_176556777655502/conda-feedstock/recipe, last modified Fri Dec 12 19:29:47 2025
# ------------------------------------------------

package:
  name: conda
  version: 25.11.1
source:
  folder: conda-src
  sha256: 280bee40bfa3dc64a294a3501ae3150fe112e0f51cf94f7a346e5cfb4b370efb
  url: https://github.com/conda/conda/releases/download/25.11.1/conda-25.11.1.tar.gz
build:
  always_include_files:
    - bin/activate
    - bin/conda
    - bin/deactivate
  number: '0'
  script: /opt/miniconda3/conda-bld/conda_1765567809749/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/bin/python
    -m pip install conda-src/ --no-deps --no-build-isolation -vv && /opt/miniconda3/conda-bld/conda_1765567809749/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/bin/python
    -m conda init --install
  string: py313hca03da5_0
requirements:
  build:
    - bzip2 1.0.8 h80987f9_6
    - c-ares 1.34.5 h2ca31fc_0
    - ca-certificates 2025.12.2 hca03da5_0
    - expat 2.7.3 h50f4ffc_4
    - gettext 0.21.0 hbdbcc25_2
    - git 2.51.0 pl5382hee26aef_1
    - icu 73.1 h313beb8_0
    - jansson 2.14 h80987f9_1
    - libcurl 8.16.0 h01d3526_0
    - libcxx 20.1.8 hd7fd590_1
    - libev 4.33 h1a28f6b_1
    - libexpat 2.7.3 h50f4ffc_4
    - libiconv 1.16 h80987f9_3
    - libidn2 2.3.8 h9681e36_0
    - libnghttp2 1.67.1 h8189af8_0
    - libssh2 1.11.1 h3e2b118_0
    - libunistring 1.3 h1799b2a_0
    - libxml2 2.13.9 h528a072_0
    - libzlib 1.3.1 h5f15de7_0
    - llvm-openmp 20.1.8 he822017_0
    - lz4-c 1.9.4 h313beb8_1
    - ncurses 6.5 hee39554_0
    - openssl 3.0.18 h9b4081a_0
    - pcre2 10.46 h1dacb4a_0
    - perl 5.40.2 0_h80987f9_perl5
    - tk 8.6.15 hcd8a7d5_0
    - xz 5.6.4 h80987f9_1
    - zlib 1.3.1 h5f15de7_0
    - zstd 1.5.7 h817c040_0
  host:
    - boltons 25.0.0 py313hca03da5_0
    - brotlicffi 1.2.0.0 py313h50f4ffc_0
    - bzip2 1.0.8 h80987f9_6
    - ca-certificates 2025.12.2 hca03da5_0
    - certifi 2025.11.12 py313hca03da5_0
    - cffi 2.0.0 py313h73c2a22_1
    - charset-normalizer 3.4.4 py313hca03da5_0
    - frozendict 2.4.6 py313haa24f5a_0
    - hatch-vcs 0.5.0 py313hca03da5_0
    - hatchling 1.27.0 py313hca03da5_1
    - idna 3.11 py313hca03da5_0
    - libcxx 20.1.8 hd7fd590_1
    - libexpat 2.7.3 h50f4ffc_4
    - libffi 3.4.4 hca03da5_1
    - libmpdec 4.0.0 h80987f9_0
    - libzlib 1.3.1 h5f15de7_0
    - menuinst 2.4.2 py313hca03da5_1
    - ncurses 6.5 hee39554_0
    - openssl 3.0.18 h9b4081a_0
    - packaging 25.0 py313hca03da5_1
    - pathspec 0.12.1 py313hca03da5_1
    - pip 25.3 pyhc872135_0
    - platformdirs 4.5.0 py313hca03da5_0
    - pluggy 1.5.0 py313hca03da5_0
    - pycparser 2.23 py313hca03da5_0
    - pysocks 1.7.1 py313hca03da5_1
    - python 3.13.11 hc7d8306_100_cp313
    - python_abi 3.13 3_cp313
    - readline 8.3 h0b18652_0
    - requests 2.32.5 py313hca03da5_1
    - ruamel.yaml 0.18.16 py313h091b9d3_0
    - ruamel.yaml.clib 0.2.14 py313h091b9d3_0
    - setuptools 80.9.0 py313hca03da5_0
    - setuptools-scm 9.2.2 py313hca03da5_0
    - sqlite 3.51.0 hab6afd1_0
    - tk 8.6.15 hcd8a7d5_0
    - tqdm 4.67.1 py313h7eb115d_1
    - trove-classifiers 2025.5.9.12 py313hca03da5_0
    - tzdata 2025b h04d1e81_0
    - urllib3 2.6.1 py313hca03da5_0
    - wheel 0.45.1 py313hca03da5_0
    - xz 5.6.4 h80987f9_1
    - zlib 1.3.1 h5f15de7_0
  run:
    - archspec >=0.2.3
    - boltons >=23.0.0
    - charset-normalizer
    - conda-libmamba-solver >=25.4.0
    - conda-package-handling >=2.2.0
    - distro >=1.5.0
    - frozendict >=2.4.2
    - jsonpatch >=1.32
    - menuinst >=2
    - packaging >=23.0
    - platformdirs >=3.10.0
    - pluggy >=1.0.0
    - pycosat >=0.6.3
    - python >=3.13,<3.14.0a0
    - python_abi 3.13.* *_cp313
    - requests >=2.28.0,<3
    - ruamel.yaml >=0.11.14,<0.19
    - setuptools >=60.0.0
    - tqdm >=4
    - truststore >=0.8.0
    - zstandard >=0.19.0
  run_constrained:
    - conda-build >=25.9
    - conda-content-trust >=0.1.1
    - conda-env >=2.6
test:
  downstreams:
    - conda-smithy
  imports:
    - conda
    - conda_env
  requires: null
about:
  description: 'Conda is an open source package management system and environment

    management system for installing multiple versions of software packages

    and their dependencies and switching easily between them. It works on

    Linux, OS X and Windows, and was created for Python programs but can

    package and distribute any software.

    '
  dev_url: https://github.com/conda/conda
  doc_url: https://docs.conda.io/projects/conda/en/stable/
  home: https://docs.conda.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: conda-src/LICENSE
  summary: OS-agnostic, system-level binary package and environment manager.
extra:
  copy_test_source_files: true
  final: true
  skip-lints:
    - missing_pip_check
    - python_build_tool_in_run
