# This file created by conda-build 3.27.0
# meta.yaml template originally from:
# /var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/abs_edf7vh9apj/clone/recipe, last modified Fri Jan 19 16:49:26 2024
# ------------------------------------------------

package:
  name: jansson
  version: '2.14'
source:
  sha256: c739578bf6b764aa0752db9a2fdadcfe921c78f1228c7ec0bb47fa804c55d17b
  url: https://github.com/akheron/jansson/archive/v2.14.tar.gz
build:
  number: '1'
  run_exports:
    - jansson >=2.14,<3.0a0
  string: h80987f9_1
requirements:
  build:
    - autoconf 2.71 pl5340h80987f9_0
    - automake 1.16.5 pl5340hca03da5_1
    - cctools_osx-arm64 949.0.1 h332cad3_25
    - clang 14.0.6 hca03da5_1
    - clang-14 14.0.6 default_h1b80db6_1
    - clang_osx-arm64 14.0.6 h9ff6fda_0
    - clangxx 14.0.6 default_h1b80db6_1
    - compiler-rt 14.0.6 h4ccfd99_0
    - compiler-rt_osx-arm64 14.0.6 h4fb70ea_0
    - gdbm 1.18 h8fe7016_4
    - ld64_osx-arm64 530 h001ce53_25
    - ldid 2.1.5 h20b2a84_3
    - libclang-cpp14 14.0.6 default_h1b80db6_1
    - libcxx 14.0.6 h848a8c0_0
    - libffi 3.4.4 hca03da5_0
    - libllvm14 14.0.6 h7ec7a93_3
    - libtool 2.4.6 h313beb8_1009
    - llvm-tools 14.0.6 hfd8c8a6_3
    - m4 1.4.18 h1230e6a_1
    - make 4.3 h620ffc9_1
    - ncurses 6.4 h313beb8_0
    - perl 5.34.0 h1a28f6b_2
    - readline 8.2 h1a28f6b_0
    - tapi 1100.0.11 h8754e6a_1
    - zlib 1.2.13 h5a0b063_0
  host: []
  run: []
test:
  commands:
    - test ! -f ${PREFIX}/lib/libjansson.a
    - test -f ${PREFIX}/lib/libjansson${SHLIB_EXT}
about:
  description: "Jansson is a C library for encoding, decoding and manipulating JSON\
    \ data.\nIts main features and design principles are:\n  Simple and intuitive\
    \ API and data model\n  Comprehensive documentation\n  No dependencies on other\
    \ libraries\n  Full Unicode support (UTF-8)\n  Extensive test suite\n"
  dev_url: https://github.com/akheron/jansson
  doc_url: https://jansson.readthedocs.io
  home: https://github.com/akheron/jansson
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Jansson is a C library for encoding, decoding and manipulating JSON data.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: ed1824f8-57b7-41a7-945e-ead0c58d65a2
  recipe-maintainers:
    - mariusvniekerk
    - xhochy
  remote_url: git@github.com:AnacondaRecipes/jansson-feedstock.git
  sha: 4bd3ab77520814613c77007a2f047f0879f8964a
