# This file created by conda-build 25.1.2
# meta.yaml template originally from:
# /Users/ec2-user/tasks/task_175818854536495/zstandard-feedstock/recipe, last modified Thu Sep 18 09:51:00 2025
# ------------------------------------------------

package:
  name: zstandard
  version: 0.24.0
source:
  patches:
    - use_system_zstd.patch
  sha256: fe3198b81c00032326342d973e526803f183f97aa9e9a98e3f897ebafe21178f
  url: https://pypi.org/packages/source/z/zstandard/zstandard-0.24.0.tar.gz
build:
  number: '0'
  script: /opt/miniconda3/conda-bld/zstandard_1758189078532/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/bin/python
    -m pip install . -vv --no-deps --no-build-isolation
  string: py313hbc14757_0
requirements:
  build:
    - cctools 986 h0dbccd1_3
    - clang 17.0.6 hdefe189_6
    - clang-17 17.0.6 default_h000693a_6
    - clang_impl_osx-arm64 17.0.6 hcb56dc5_4
    - clang_osx-arm64 17.0.6 hcb56dc5_4
    - clangxx 17.0.6 default_h000693a_6
    - compiler-rt 17.0.6 h6a6761b_1
    - compiler-rt_osx-arm64 17.0.6 h6a6761b_1
    - icu 73.1 h313beb8_0
    - ld64 711 h3c27c41_3
    - libclang-cpp17 17.0.6 default_h000693a_6
    - libcxx 17.0.6 he5c5206_4
    - libcxx-devel 17.0.6 hbf97328_4
    - libffi 3.4.4 hca03da5_1
    - libiconv 1.16 h80987f9_3
    - libllvm17 17.0.6 h07a7f36_6
    - libxml2 2.13.8 h0b34f26_0
    - llvm 17.0.6 h0bf6939_6
    - llvm-tools 17.0.6 hcb83754_6
    - lz4-c 1.9.4 h313beb8_1
    - macosx_deployment_target_osx-arm64 12.1 h1c4a9a5_1
    - tapi 1100.0.11 h8754e6a_1
    - xz 5.6.4 h80987f9_1
    - zlib 1.2.13 ha1e9f54_2
    - zstd 1.5.6 hfb09047_0
  host:
    - bzip2 1.0.8 h80987f9_6
    - ca-certificates 2025.9.9 hca03da5_0
    - cffi 1.17.1 py313h3eb5a62_1
    - expat 2.7.1 h313beb8_0
    - libcxx 20.1.8 h8869778_0
    - libffi 3.4.4 hca03da5_1
    - libmpdec 4.0.0 h80987f9_0
    - libzlib 1.3.1 h5f15de7_0
    - lz4-c 1.9.4 h313beb8_1
    - ncurses 6.5 hee39554_0
    - openssl 3.0.17 h4ee41c1_0
    - packaging 25.0 py313hca03da5_0
    - pip 25.2 pyhc872135_0
    - pycparser 2.23 py313hca03da5_0
    - python 3.13.7 hc28b8d9_100_cp313
    - python_abi 3.13 1_cp313
    - readline 8.3 h0b18652_0
    - setuptools 78.1.1 py313hca03da5_0
    - sqlite 3.50.2 h79febb2_1
    - tk 8.6.15 hcd8a7d5_0
    - tzdata 2025b h04d1e81_0
    - wheel 0.45.1 py313hca03da5_0
    - xz 5.6.4 h80987f9_1
    - zlib 1.3.1 h5f15de7_0
    - zstd 1.5.7 h817c040_0
  run:
    - __osx >=12.1
    - cffi >=1.17
    - python >=3.13,<3.14.0a0
    - python_abi 3.13.* *_cp313
    - zstd >=1.5.7,<1.5.8.0a0
    - zstd >=1.5.7,<1.6.0a0
test:
  commands:
    - pip check
  imports:
    - zstandard
  requires:
    - pip
about:
  description: 'This project provides Python bindings for interfacing with the

    Zstandard compression library. A C extension and CFFI interface are

    provided.

    '
  dev_url: https://github.com/indygreg/python-zstandard
  doc_url: https://python-zstandard.readthedocs.io
  home: https://github.com/indygreg/python-zstandard
  license: BSD-3-Clause
  license_family: BSD
  license_file:
    - LICENSE
    - zstd/LICENSE
  summary: Zstandard bindings for Python
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - rmax
    - xhochy
