# This file created by conda-build 25.1.2
# meta.yaml template originally from:
# /Users/ec2-user/tasks/task_176416514063873/pydantic-settings-feedstock/recipe, last modified Wed Nov 26 13:52:22 2025
# ------------------------------------------------

package:
  name: pydantic-settings
  version: 2.12.0
source:
  sha256: 005538ef951e3c2a68e1c08b292b5f2e71490def8589d4221b95dab00dafcfd0
  url: https://pypi.org/packages/source/p/pydantic-settings/pydantic_settings-2.12.0.tar.gz
build:
  number: '0'
  script: /opt/miniconda3/conda-bld/pydantic-settings_1764165151428/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/bin/python
    -m pip install . -vv --no-deps --no-build-isolation
  string: py313hca03da5_0
requirements:
  host:
    - bzip2 1.0.8 h80987f9_6
    - ca-certificates 2025.11.4 hca03da5_0
    - expat 2.7.3 h982b769_0
    - hatchling 1.27.0 py313hca03da5_1
    - libcxx 20.1.8 hd7fd590_1
    - libffi 3.4.4 hca03da5_1
    - libmpdec 4.0.0 h80987f9_0
    - libzlib 1.3.1 h5f15de7_0
    - ncurses 6.5 hee39554_0
    - openssl 3.0.18 h9b4081a_0
    - packaging 25.0 py313hca03da5_1
    - pathspec 0.12.1 py313hca03da5_1
    - pip 25.3 pyhc872135_0
    - pluggy 1.5.0 py313hca03da5_0
    - python 3.13.9 hc7d8306_100_cp313
    - python_abi 3.13 2_cp313
    - readline 8.3 h0b18652_0
    - setuptools 80.9.0 py313hca03da5_0
    - sqlite 3.51.0 hab6afd1_0
    - tk 8.6.15 hcd8a7d5_0
    - trove-classifiers 2025.5.9.12 py313hca03da5_0
    - tzdata 2025b h04d1e81_0
    - wheel 0.45.1 py313hca03da5_0
    - xz 5.6.4 h80987f9_1
    - zlib 1.3.1 h5f15de7_0
  run:
    - pydantic >=2.7.0
    - python >=3.13,<3.14.0a0
    - python-dotenv >=0.21.0
    - python_abi 3.13.* *_cp313
    - typing-inspection >=0.4.0
  run_constrained:
    - azure-identity >=1.16.0
    - azure-keyvault-secrets >=4.8.0
    - boto3>=1.35.0
    - google-cloud-secret-manager>=2.23.1
    - pyyaml >=6.0.1
    - tomli >=2.0.1
test:
  commands:
    - pip check
    - pytest -v tests --ignore=tests/test_docs.py --ignore=tests/test_source_cli.py
  imports:
    - pydantic_settings
  requires:
    - pip
    - pytest
    - pytest-mock
  source_files:
    - tests
about:
  description: 'Pydantic Settings provides optional Pydantic features for loading
    a settings or config class from environment

    variables or secrets files.

    '
  dev_url: https://github.com/pydantic/pydantic-settings
  doc_url: https://docs.pydantic.dev/latest/usage/pydantic_settings
  home: https://github.com/pydantic/pydantic-settings
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Settings management using Pydantic
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - fhoehle
    - jan-janssen
