# This file created by conda-build 24.5.1
# meta.yaml template originally from:
# /var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/abs_56qkzx5803/clone/recipe, last modified Tue Aug  6 00:24:25 2024
# ------------------------------------------------

package:
  name: gettext
  version: 0.21.0
source:
  - patches:
      - 0000-Add-ax_with_curses.m4-and-try-to-use-it.patch
      - use-acinit-for-libtextstyle.patch
    sha256: d20fcbb537e02dcf1383197ba05bd0734ef7bf5db06bdb241eb69b7d16b73192
    url: https://ftp.gnu.org/pub/gnu/gettext/gettext-0.21.tar.xz
build:
  env:
    - SKIP_GNULIB=--skip-gnulib
  number: '2'
  run_exports:
    - gettext >=0.21.0,<1.0a0
  string: hbdbcc25_2
requirements:
  build:
    - autoconf 2.71 pl5340h80987f9_0
    - autoconf-archive 2021.02.19 hd3eb1b0_0
    - automake 1.16.5 pl5340hca03da5_1
    - ca-certificates 2024.7.2 hca03da5_0
    - cctools_osx-arm64 949.0.1 h332cad3_25
    - clang 14.0.6 hca03da5_1
    - clang-14 14.0.6 default_h1b80db6_1
    - clang_osx-arm64 14.0.6 h9ff6fda_0
    - clangxx 14.0.6 default_h1b80db6_1
    - clangxx_osx-arm64 14.0.6 h72866fe_0
    - compiler-rt 14.0.6 h4ccfd99_0
    - compiler-rt_osx-arm64 14.0.6 h4fb70ea_0
    - gdbm 1.18 h8fe7016_4
    - ld64_osx-arm64 530 h001ce53_25
    - ldid 2.1.5 h20b2a84_3
    - libclang-cpp14 14.0.6 default_h1b80db6_1
    - libcxx 14.0.6 h848a8c0_0
    - libffi 3.4.4 hca03da5_1
    - libiconv 1.16 h80987f9_3
    - libidn2 2.3.4 h80987f9_0
    - libllvm14 14.0.6 h7ec7a93_3
    - libtool 2.4.6 h313beb8_1009
    - libunistring 0.9.10 h1a28f6b_0
    - llvm-tools 14.0.6 hfd8c8a6_3
    - m4 1.4.18 h1230e6a_1
    - make 4.3 h620ffc9_1
    - ncurses 6.4 h313beb8_0
    - openssl 3.0.14 h80987f9_0
    - patch 2.7.6 h1a28f6b_1001
    - perl 5.34.0 h1a28f6b_2
    - pkg-config 0.29.2 h1a28f6b_0
    - readline 8.2 h1a28f6b_0
    - tapi 1100.0.11 h8754e6a_1
    - wget 1.21.4 h3e2b118_1
    - zlib 1.2.13 h18a0788_1
  host:
    - icu 73.1 h313beb8_0
    - libcxx 14.0.6 h848a8c0_0
    - libiconv 1.16 h80987f9_3
    - libxml2 2.13.1 h0b34f26_2
    - llvm-openmp 14.0.6 hc6e5704_0
    - ncurses 6.4 h313beb8_0
    - xz 5.4.6 h80987f9_1
    - zlib 1.2.13 h18a0788_1
  run:
    - libcxx >=14.0.6
    - libiconv >=1.16,<2.0a0
    - libxml2 >=2.13.1,<2.14.0a0
    - llvm-openmp >=14.0.6
    - ncurses >=6.4,<7.0a0
test:
  commands:
    - test -f ${PREFIX}/lib/libgettextlib$SHLIB_EXT
    - test -f ${PREFIX}/lib/libgettextpo$SHLIB_EXT
    - test -f ${PREFIX}/lib/libgettextsrc$SHLIB_EXT
    - test -f ${PREFIX}/lib/libintl$SHLIB_EXT
about:
  description: 'GNU gettext is an important step for the GNU Translation Project,

    as it is an asset on which we may build many other steps.

    This package offers to programmers, translators, and even users,

    a well integrated set of tools and documentation.

    Specifically, the GNU gettext utilities are a set of tools

    that provides a framework to help other GNU packages produce multi-lingual messages.

    These tools include a set of conventions about how programs should be written

    to support message catalogs, a directory and file naming organization for the
    message catalogs themselves,

    a runtime library supporting the retrieval of translated messages, and a few stand-alone
    programs

    to massage in various ways the sets of translatable strings, or already translated
    strings.

    '
  dev_url: https://git.savannah.gnu.org/gitweb/?p=gettext.git
  doc_url: https://www.gnu.org/software/gettext/manual/gettext.html
  home: https://www.gnu.org/software/gettext/
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: Internationalization package
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 56efb876-d726-4e45-8ce3-4f9cd220d3ae
  recipe-maintainers:
    - ocefpaf
    - scopatz
  remote_url: git@github.com:AnacondaRecipes/gettext-feedstock.git
  sha: 45586482550e35d7c8ebfcc1183c3600f7b8c625
