# This file created by conda-build 25.1.2
# meta.yaml template originally from:
# /Users/ec2-user/tasks/task_176061334504913/typing-inspection-feedstock/recipe, last modified Thu Oct 16 11:29:16 2025
# ------------------------------------------------

package:
  name: typing-inspection
  version: 0.4.2
source:
  sha256: ba561c48a67c5958007083d386c3295464928b01faa735ab8547c5692e87f464
  url: https://pypi.org/packages/source/t/typing-inspection/typing_inspection-0.4.2.tar.gz
build:
  number: '0'
  script: /opt/miniconda3/conda-bld/typing-inspection_1760614169744/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/bin/python
    -m pip install . -vv --no-deps --no-build-isolation
  string: py313hca03da5_0
requirements:
  host:
    - bzip2 1.0.8 h80987f9_6
    - ca-certificates 2025.9.9 hca03da5_0
    - expat 2.7.1 h313beb8_0
    - hatchling 1.27.0 py313hca03da5_0
    - libcxx 20.1.8 h8869778_0
    - libffi 3.4.4 hca03da5_1
    - libmpdec 4.0.0 h80987f9_0
    - libzlib 1.3.1 h5f15de7_0
    - ncurses 6.5 hee39554_0
    - openssl 3.0.18 h9b4081a_0
    - packaging 25.0 py313hca03da5_0
    - pathspec 0.12.1 py313hca03da5_0
    - pip 25.2 pyhc872135_1
    - pluggy 1.5.0 py313hca03da5_0
    - python 3.13.7 hc28b8d9_100_cp313
    - python_abi 3.13 1_cp313
    - readline 8.3 h0b18652_0
    - setuptools 80.9.0 py313hca03da5_0
    - sqlite 3.50.2 h79febb2_1
    - tk 8.6.15 hcd8a7d5_0
    - trove-classifiers 2025.5.9.12 py313hca03da5_0
    - tzdata 2025b h04d1e81_0
    - wheel 0.45.1 py313hca03da5_0
    - xz 5.6.4 h80987f9_1
    - zlib 1.3.1 h5f15de7_0
  run:
    - python >=3.13,<3.14.0a0
    - python_abi 3.13.* *_cp313
    - typing_extensions >=4.12.0
test:
  commands:
    - pip check
    - pytest . -v
  imports:
    - typing_inspection
  requires:
    - pip
    - pytest
  source_files:
    - tests/*
about:
  description: 'A collection of runtime typing introspection tools, including a

    `typing_inspect` module that provides a consistent interface for

    inspecting types across different Python versions.

    '
  dev_url: https://github.com/pydantic/typing-inspection
  doc_url: https://pydantic.github.io/typing-inspection/0.4
  home: https://github.com/pydantic/typing-inspection
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Runtime typing introspection tools
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - jan-janssen
