# This file created by conda-build 25.1.2
# ------------------------------------------------

package:
  name: libsolv
  version: 0.7.30
source:
  patches:
    - patches/conda_variant_priorization.patch
    - patches/no_error_subdir_mismatch.patch
    - patches/pcre2-compat.patch
  sha256: ce4aa2f0e3c5c9ab99dced6a1810af3f670f1b98892394edc68ccabe7b272133
  url: https://github.com/openSUSE/libsolv/archive/0.7.30.tar.gz
build:
  noarch: false
  noarch_python: false
  number: '2'
  script: install.sh
  string: ha443353_2
requirements:
  build:
    - bzip2 1.0.8 h80987f9_6
    - c-ares 1.34.5 h2ca31fc_0
    - ca-certificates 2025.9.9 hca03da5_0
    - cctools 986 h0dbccd1_3
    - clang 17.0.6 hdefe189_6
    - clang-17 17.0.6 default_h000693a_6
    - clang_impl_osx-arm64 17.0.6 hcb56dc5_4
    - clang_osx-arm64 17.0.6 hcb56dc5_4
    - clangxx 17.0.6 default_h000693a_6
    - clangxx_impl_osx-arm64 17.0.6 h39b79ac_4
    - clangxx_osx-arm64 17.0.6 hcb56dc5_4
    - cmake 3.31.2 h89d4fe9_0
    - compiler-rt 17.0.6 h6a6761b_1
    - compiler-rt_osx-arm64 17.0.6 h6a6761b_1
    - expat 2.7.1 h313beb8_0
    - ld64 711 h3c27c41_3
    - libclang-cpp17 17.0.6 default_h000693a_6
    - libcurl 8.15.0 hcdd2897_0
    - libcxx 17.0.6 he5c5206_4
    - libcxx-devel 17.0.6 hbf97328_4
    - libev 4.33 h1a28f6b_1
    - libffi 3.4.4 hca03da5_1
    - libiconv 1.16 h80987f9_3
    - libllvm17 17.0.6 hac7df47_1
    - libmpdec 4.0.0 h80987f9_0
    - libnghttp2 1.57.0 h62f6fdd_0
    - libssh2 1.11.1 h3e2b118_0
    - libuv 1.48.0 h80987f9_0
    - libzlib 1.3.1 h5f15de7_0
    - llvm 17.0.6 h8abdc9b_1
    - llvm-tools 17.0.6 h7e95266_1
    - lz4-c 1.9.4 h313beb8_1
    - macosx_deployment_target_osx-arm64 12.1 h1c4a9a5_1
    - ncurses 6.5 hee39554_0
    - ninja 1.12.1 hca03da5_0
    - ninja-base 1.12.1 h48ca7d4_0
    - openssl 3.0.18 h9b4081a_0
    - pkg-config 0.29.2 h1a28f6b_0
    - python 3.14.0 h07d03ab_100_cp314
    - python_abi 3.14 1_cp314
    - readline 8.3 h0b18652_0
    - rhash 1.4.3 h02f6b3c_0
    - sqlite 3.50.2 h79febb2_1
    - tapi 1100.0.11 h8754e6a_1
    - tk 8.6.15 hcd8a7d5_0
    - tzdata 2025b h04d1e81_0
    - xz 5.6.4 h80987f9_1
    - zlib 1.3.1 h5f15de7_0
    - zstd 1.5.7 h817c040_0
  host:
    - bzip2 1.0.8 h80987f9_6
    - libcxx 20.1.8 h8869778_0
    - pcre2 10.46 h1dacb4a_0
    - zlib 1.2.13 ha1e9f54_2
  run:
    - __osx >=12.1
    - libcxx >=17
    - pcre2 >=10.46,<10.47.0a0
    - zlib >=1.2.13,<2.0a0
test:
  commands:
    - test -f ${PREFIX}/lib/libsolv${SHLIB_EXT}
    - test -f ${PREFIX}/lib/libsolvext${SHLIB_EXT}
    - test -f ${PREFIX}/include/solv/repo.h
    - dumpsolv -h
about:
  description: 'libsolv, a free package dependency solver using a satisfiability algorithm.

    '
  dev_url: https://github.com/openSUSE/libsolv
  doc_url: https://github.com/openSUSE/libsolv/tree/master/doc
  home: https://github.com/openSUSE/libsolv
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.BSD
  summary: Library for solving packages and reading repositories
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - JohanMabille
    - SylvainCorlay
    - adriendelsalle
    - davidbrochart
    - wolfv
