# This file created by conda-build 25.1.2
# meta.yaml template originally from:
# /Users/ec2-user/tasks/task_176488747967798/anaconda-cli-base-feedstock/recipe, last modified Thu Dec  4 22:49:39 2025
# ------------------------------------------------

package:
  name: anaconda-cli-base
  version: 0.7.0
source:
  sha256: 4ebec5d913039b6ac208a4c6abed737f7ad1f311f54c14b768bd5cb266092207
  url: https://pypi.org/packages/source/a/anaconda-cli-base/anaconda_cli_base-0.7.0.tar.gz
build:
  entry_points:
    - anaconda = anaconda_cli_base.cli:app
  number: '0'
  script: /opt/miniconda3/conda-bld/anaconda-cli-base_1764888589923/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/bin/python
    -m pip install . -vv --no-deps --no-build-isolation
  string: py313hca03da5_0
requirements:
  host:
    - bzip2 1.0.8 h80987f9_6
    - ca-certificates 2025.12.2 hca03da5_0
    - expat 2.7.3 h982b769_0
    - hatch-vcs 0.5.0 py313hca03da5_0
    - hatchling 1.27.0 py313hca03da5_1
    - libcxx 20.1.8 hd7fd590_1
    - libffi 3.4.4 hca03da5_1
    - libmpdec 4.0.0 h80987f9_0
    - libzlib 1.3.1 h5f15de7_0
    - ncurses 6.5 hee39554_0
    - openssl 3.0.18 h9b4081a_0
    - packaging 25.0 py313hca03da5_1
    - pathspec 0.12.1 py313hca03da5_1
    - pip 25.3 pyhc872135_0
    - pluggy 1.5.0 py313hca03da5_0
    - python 3.13.10 hc7d8306_100_cp313
    - python_abi 3.13 3_cp313
    - readline 8.3 h0b18652_0
    - setuptools 80.9.0 py313hca03da5_0
    - setuptools-scm 9.2.2 py313hca03da5_0
    - sqlite 3.51.0 hab6afd1_0
    - tk 8.6.15 hcd8a7d5_0
    - trove-classifiers 2025.5.9.12 py313hca03da5_0
    - tzdata 2025b h04d1e81_0
    - wheel 0.45.1 py313hca03da5_0
    - xz 5.6.4 h80987f9_1
    - zlib 1.3.1 h5f15de7_0
  run:
    - click
    - packaging >=23.0
    - pydantic-settings >=2.3
    - python >=3.13,<3.14.0a0
    - python_abi 3.13.* *_cp313
    - readchar
    - rich
    - tomli
    - typer >=0.17
  run_constrained:
    - anaconda-auth >=0.12.0
    - anaconda-client >=1.13.0
    - anaconda-cloud-cli >=0.3.0
test:
  commands:
    - pip check
    - anaconda -h
    - anaconda -V
    - python -c "from anaconda_cli_base import __version__; assert __version__ ==
      \"0.7.0\""
    - python -c "from importlib.metadata import version; assert(version('anaconda-cli-base')=='0.7.0')"
    - pytest -v tests
  imports:
    - anaconda_cli_base
  requires:
    - pip
    - pytest
    - pytest-mock
    - types-requests
  source_files:
    - tests
about:
  description: A base CLI entrypoint supporting Anaconda CLI plugins
  dev_url: https://pypi.org/project/anaconda-cli-base
  doc_url: https://pypi.org/project/anaconda-cli-base
  home: https://anaconda.cloud
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A base CLI entrypoint supporting Anaconda CLI plugins
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - albertdefusco
    - mattkram
