# This file created by conda-build 25.1.2
# meta.yaml template originally from:
# /Users/ec2-user/tasks/task_176243157395224/pygments-feedstock/recipe, last modified Thu Nov  6 12:19:35 2025
# ------------------------------------------------

package:
  name: pygments
  version: 2.19.2
source:
  sha256: 636cb2477cec7f8952536970bc533bc43743542f70392ae026374600add5b887
  url: https://pypi.org/packages/source/p/pygments/pygments-2.19.2.tar.gz
build:
  entry_points:
    - pygmentize = pygments.cmdline:main
  number: '0'
  script: /opt/miniconda3/conda-bld/pygments_1762431584667/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/bin/python
    -m pip install . --no-deps --no-build-isolation
  string: py313hca03da5_0
requirements:
  host:
    - bzip2 1.0.8 h80987f9_6
    - ca-certificates 2025.11.4 hca03da5_0
    - expat 2.7.3 h982b769_0
    - hatchling 1.27.0 py313hca03da5_1
    - libcxx 20.1.8 hd7fd590_1
    - libffi 3.4.4 hca03da5_1
    - libmpdec 4.0.0 h80987f9_0
    - libzlib 1.3.1 h5f15de7_0
    - ncurses 6.5 hee39554_0
    - openssl 3.0.18 h9b4081a_0
    - packaging 25.0 py313hca03da5_1
    - pathspec 0.12.1 py313hca03da5_1
    - pip 25.2 pyhc872135_1
    - pluggy 1.5.0 py313hca03da5_0
    - python 3.13.9 hc7d8306_100_cp313
    - python_abi 3.13 1_cp313
    - readline 8.3 h0b18652_0
    - setuptools 80.9.0 py313hca03da5_0
    - sqlite 3.50.2 h79febb2_1
    - tk 8.6.15 hcd8a7d5_0
    - trove-classifiers 2025.5.9.12 py313hca03da5_0
    - tzdata 2025b h04d1e81_0
    - wheel 0.45.1 py313hca03da5_0
    - xz 5.6.4 h80987f9_1
    - zlib 1.3.1 h5f15de7_0
  run:
    - python >=3.13,<3.14.0a0
    - python_abi 3.13.* *_cp313
  run_constrained: []
test:
  commands:
    - pip check
    - pygmentize -h
    - pytest -v tests  --ignore=tests/contrast/test_contrasts.py  --deselect=tests/test_basic_api.py::test_lexer_classes
  imports:
    - pygments
    - pygments.filters
    - pygments.formatters
    - pygments.lexers
    - pygments.plugin
    - pygments.styles
  requires:
    - pip
    - pytest
  source_files:
    - tests
about:
  description: 'This is the source of Pygments. It is

    a generic syntax highlighter written in Python

    that supports over 500 languages and text formats,

    for use in code hosting, forums, wikis or other applications

    that need to prettify source code.

    '
  dev_url: https://github.com/pygments/pygments
  doc_url: https://pygments.org/docs
  home: https://pygments.org
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Pygments is a generic syntax highlighter suitable for use in code hosting,
    forums, wikis or other applications that need to prettify source code.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - jakirkham
    - ocefpaf
    - pelson
    - scopatz
