# This file created by conda-build 25.1.2
# meta.yaml template originally from:
# /Users/ec2-user/tasks/task_176286299600708/tqdm-feedstock/recipe, last modified Tue Nov 11 12:15:38 2025
# ------------------------------------------------

package:
  name: tqdm
  version: 4.67.1
source:
  sha256: f8aef9c52c08c13a65f30ea34f4e5aac3fd1a34959879d7e59e63027286627f2
  url: https://pypi.org/packages/source/t/tqdm/tqdm-4.67.1.tar.gz
build:
  entry_points:
    - tqdm = tqdm.cli:main
  number: '1'
  script: /opt/miniconda3/conda-bld/tqdm_1762863348900/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/bin/python
    -m pip install . --no-deps --no-build-isolation -vv
  string: py313h7eb115d_1
requirements:
  host:
    - bzip2 1.0.8 h80987f9_6
    - ca-certificates 2025.11.4 hca03da5_0
    - expat 2.7.3 h982b769_0
    - libcxx 20.1.8 hd7fd590_1
    - libffi 3.4.4 hca03da5_1
    - libmpdec 4.0.0 h80987f9_0
    - libzlib 1.3.1 h5f15de7_0
    - ncurses 6.5 hee39554_0
    - openssl 3.0.18 h9b4081a_0
    - packaging 25.0 py313hca03da5_1
    - pip 25.2 pyhc872135_1
    - python 3.13.9 hc7d8306_100_cp313
    - python_abi 3.13 1_cp313
    - readline 8.3 h0b18652_0
    - setuptools 80.9.0 py313hca03da5_0
    - setuptools-scm 8.3.1 py313hca03da5_1
    - setuptools_scm 8.3.1 hd3eb1b0_1
    - sqlite 3.51.0 hab6afd1_0
    - tk 8.6.15 hcd8a7d5_0
    - toml 0.10.2 pyhd3eb1b0_0
    - tzdata 2025b h04d1e81_0
    - wheel 0.45.1 py313hca03da5_0
    - xz 5.6.4 h80987f9_1
    - zlib 1.3.1 h5f15de7_0
  run:
    - python >=3.13,<3.14.0a0
    - python_abi 3.13.* *_cp313
  run_constrained:
    - ipywidgets >=6
test:
  commands:
    - pip check
    - tqdm --help
    - tqdm -v | rg 4.67.1
    - pytest -k "not tests_perf" tests/ -W ignore::FutureWarning  --deselect=tests/tests_pandas.py::test_pandas_leave
  imports:
    - tqdm
  requires:
    - dask-core
    - numpy
    - pandas
    - pip
    - pytest >=6
    - pytest-asyncio >=0.24
    - pytest-timeout
    - pytest-xdist
    - rich
    - ripgrep
  source_files:
    - pyproject.toml
    - tests
about:
  description: A Fast, Extensible Progress Bar for Python and CLI
  dev_url: https://github.com/tqdm/tqdm
  doc_url: https://tqdm.github.io/
  home: https://tqdm.github.io/
  license: MPL-2.0 AND MIT
  license_family: MOZILLA
  license_file: LICENCE
  summary: A Fast, Extensible Progress Meter
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - casperdcl
    - pmlandwehr
