# This file created by conda-build 25.1.2
# meta.yaml template originally from:
# /Users/ec2-user/tasks/task_175803909428575/zstd-feedstock/recipe, last modified Tue Sep 16 16:12:07 2025
# ------------------------------------------------

package:
  name: zstd
  version: 1.5.7
source:
  sha256: 37d7284556b20954e56e1ca85b80226768902e2edabd3b649e9e72c0c9012ee3
  url: https://github.com/facebook/zstd/archive/v1.5.7.tar.gz
build:
  number: '0'
  run_exports:
    - zstd >=1.5.7,<1.6.0a0
  string: h817c040_0
requirements:
  build:
    - clang_bootstrap_osx-arm64 17.0.6 ha993bc6_4
    - cmake-no-system 3.25.3 h313beb8_0
    - libcxx 20.1.8 h8869778_0
    - macosx_deployment_target_osx-arm64 12.1 h1c4a9a5_1
    - make 4.3 h620ffc9_1
    - ninja-base 1.12.1 h48ca7d4_0
  host:
    - libcxx 20.1.8 h8869778_0
    - libzlib 1.3.1 h5f15de7_0
    - lz4-c 1.9.4 h313beb8_1
    - xz 5.6.4 h80987f9_1
    - zlib 1.3.1 h5f15de7_0
  run:
    - __osx >=12.1
    - libzlib >=1.3.1,<2.0a0
    - lz4-c >=1.9.4,<1.10.0a0
    - xz >=5.6.4,<6.0a0
test:
  commands:
    - zstd -be -i5
    - test -f ${PREFIX}/include/zstd.h
    - test -f ${PREFIX}/lib/libzstd.a
    - test -f ${PREFIX}/lib/libzstd.dylib
    - export PKG_CONFIG_PATH=$PREFIX/lib/pkgconfig
    - test -f ${PREFIX}/lib/pkgconfig/libzstd.pc
    - pkg-config --cflags libzstd
  requires:
    - pkg-config
about:
  description: 'Zstandard is a real-time compression algorithm, providing high compression

    ratios. It offers a very wide range of compression / speed trade-off, while

    being backed by a very fast decoder. It also offers a special mode for

    small data, called dictionary compression, and can create dictionaries from

    any sample set. Zstandard library is provided as open source software using

    a BSD license.

    '
  dev_url: https://github.com/facebook/zstd
  doc_url: https://facebook.github.io/zstd/zstd_manual.html
  home: https://facebook.github.io/zstd/
  license: BSD-3-Clause AND GPL-2.0-or-later
  license_family: BSD
  license_file: LICENSE
  summary: Zstandard - Fast real-time compression algorithm
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - chenghlee
    - msarahan
    - rmax
    - xhochy
