# This file created by conda-build 25.1.2
# meta.yaml template originally from:
# /Users/ec2-user/tasks/task_176036261262413/libidn2-feedstock/recipe, last modified Mon Oct 13 14:04:49 2025
# ------------------------------------------------

package:
  name: libidn2
  version: 2.3.8
source:
  sha256: f557911bf6171621e1f72ff35f5b1825bb35b52ed45325dcdee931e5d3c0787a
  url: https://ftp.gnu.org/gnu/libidn/libidn2-2.3.8.tar.gz
build:
  number: '0'
  run_exports:
    - libidn2 >=2,<3.0a0
  string: h9681e36_0
requirements:
  build:
    - cctools 986 h0dbccd1_3
    - clang 17.0.6 hdefe189_6
    - clang-17 17.0.6 default_h000693a_6
    - clang_impl_osx-arm64 17.0.6 hcb56dc5_4
    - clang_osx-arm64 17.0.6 hcb56dc5_4
    - clangxx 17.0.6 default_h000693a_6
    - compiler-rt 17.0.6 h6a6761b_1
    - compiler-rt_osx-arm64 17.0.6 h6a6761b_1
    - gnuconfig 2021.05.24 hd3eb1b0_0
    - icu 73.1 h313beb8_0
    - ld64 711 h3c27c41_3
    - libclang-cpp17 17.0.6 default_h000693a_6
    - libcxx 17.0.6 he5c5206_4
    - libcxx-devel 17.0.6 hbf97328_4
    - libffi 3.4.4 hca03da5_1
    - libiconv 1.16 h80987f9_3
    - libllvm17 17.0.6 h07a7f36_6
    - libxml2 2.13.8 h0b34f26_0
    - llvm 17.0.6 h0bf6939_6
    - llvm-tools 17.0.6 hcb83754_6
    - lz4-c 1.9.4 h313beb8_1
    - macosx_deployment_target_osx-arm64 12.1 h1c4a9a5_1
    - make 4.3 h620ffc9_1
    - pkg-config 0.29.2 h1a28f6b_0
    - tapi 1100.0.11 h8754e6a_1
    - xz 5.6.4 h80987f9_1
    - zlib 1.2.13 ha1e9f54_2
    - zstd 1.5.6 hfb09047_0
  host:
    - gettext 0.21.0 hbdbcc25_2
    - icu 73.1 h313beb8_0
    - libcxx 20.1.8 h8869778_0
    - libiconv 1.16 h80987f9_3
    - libunistring 1.3 h1799b2a_0
    - libxml2 2.13.8 h0b34f26_0
    - libzlib 1.3.1 h5f15de7_0
    - llvm-openmp 20.1.8 he822017_0
    - ncurses 6.5 hee39554_0
    - xz 5.6.4 h80987f9_1
    - zlib 1.3.1 h5f15de7_0
  run:
    - __osx >=12.1
    - gettext >=0.21.0,<1.0a0
    - libiconv >=1.16,<2.0a0
    - libunistring >=1,<2.0a0
test:
  commands:
    - test -f "${PREFIX}/include/idn2.h"
    - test -f "${PREFIX}/lib/libidn2${SHLIB_EXT}"
    - test ! -f "${PREFIX}/lib/libidn2.a"
about:
  description: Library for internationalized domain names (IDNA2008) support
  dev_url: https://gitlab.com/libidn/libidn2
  doc_url: https://libidn.gitlab.io/libidn2/manual/libidn2.html
  home: https://www.gnu.org/software/libidn/#libidn2
  license: LGPL-2.0 AND LGPL-3.0-or-later AND GPL-3.0-or-later
  license_family: OTHER
  license_file: COPYING
  summary: Library for internationalized domain names (IDNA2008) support
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - chenghlee
    - hmaarrfk
