# This file created by conda-build 25.1.2
# meta.yaml template originally from:
# /Users/ec2-user/tasks/task_176235665535040/platformdirs-feedstock/recipe, last modified Wed Nov  5 15:30:57 2025
# ------------------------------------------------

package:
  name: platformdirs
  version: 4.5.0
source:
  sha256: 70ddccdd7c99fc5942e9fc25636a8b34d04c24b335100223152c2803e4063312
  url: https://pypi.org/packages/source/p/platformdirs/platformdirs-4.5.0.tar.gz
build:
  number: '0'
  script: /opt/miniconda3/conda-bld/platformdirs_1762356666077/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/bin/python
    -m pip install . --no-deps --no-build-isolation -vv
  string: py313hca03da5_0
requirements:
  host:
    - bzip2 1.0.8 h80987f9_6
    - ca-certificates 2025.11.4 hca03da5_0
    - expat 2.7.3 h982b769_0
    - hatch-vcs 0.5.0 py313hca03da5_0
    - hatchling 1.27.0 py313hca03da5_1
    - libcxx 20.1.8 hd7fd590_1
    - libffi 3.4.4 hca03da5_1
    - libmpdec 4.0.0 h80987f9_0
    - libzlib 1.3.1 h5f15de7_0
    - ncurses 6.5 hee39554_0
    - openssl 3.0.18 h9b4081a_0
    - packaging 25.0 py313hca03da5_1
    - pathspec 0.12.1 py313hca03da5_1
    - pip 25.2 pyhc872135_1
    - pluggy 1.5.0 py313hca03da5_0
    - python 3.13.9 hc7d8306_100_cp313
    - python_abi 3.13 1_cp313
    - readline 8.3 h0b18652_0
    - setuptools 80.9.0 py313hca03da5_0
    - setuptools-scm 8.3.1 py313hca03da5_1
    - sqlite 3.50.2 h79febb2_1
    - tk 8.6.15 hcd8a7d5_0
    - trove-classifiers 2025.5.9.12 py313hca03da5_0
    - tzdata 2025b h04d1e81_0
    - wheel 0.45.1 py313hca03da5_0
    - xz 5.6.4 h80987f9_1
    - zlib 1.3.1 h5f15de7_0
  run:
    - python >=3.13,<3.14.0a0
    - python_abi 3.13.* *_cp313
test:
  commands:
    - pip check
    - pytest tests -vv
  imports:
    - platformdirs
  requires:
    - appdirs
    - pip
    - pytest
    - pytest-mock
  source_files:
    - tests
about:
  description: 'About A small Python module for determining appropriate

    platform-specific dirs, e.g. a "user data dir".

    '
  dev_url: https://github.com/platformdirs/platformdirs
  doc_url: https://platformdirs.readthedocs.io
  home: https://github.com/platformdirs/platformdirs
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A small Python module for determining appropriate platform-specific dirs,
    e.g. a "user data dir".
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - adament
    - gaborbernat
