# This file created by conda-build 24.9.0
# meta.yaml template originally from:
# /var/folders/k1/30mswbxs7r1g6zwn8y4fyt500000gp/T/abs_04awf4inmn/clone/recipe, last modified Tue Aug 12 04:26:57 2025
# ------------------------------------------------

package:
  name: fmt
  version: 11.2.0
source:
  patches: null
  sha256: bc23066d87ab3168f27cef3e97d545fa63314f5c79df5ea444d41d56f962c6af
  url: https://github.com/fmtlib/fmt/archive/11.2.0.tar.gz
build:
  number: '0'
  run_exports:
    - fmt >=11.2.0,<12.0a0
  string: h643473a_0
requirements:
  build:
    - bzip2 1.0.8 h80987f9_6
    - c-ares 1.19.1 h80987f9_0
    - ca-certificates 2025.7.15 hca03da5_0
    - cctools_osx-arm64 949.0.1 h69e4071_26
    - clang 14.0.6 hca03da5_2
    - clang-14 14.0.6 default_h1b80db6_2
    - clang_osx-arm64 14.0.6 h9ff6fda_0
    - clangxx 14.0.6 default_h1b80db6_2
    - clangxx_osx-arm64 14.0.6 h72866fe_0
    - cmake 3.31.2 h89d4fe9_0
    - compiler-rt 14.0.6 h4ccfd99_0
    - compiler-rt_osx-arm64 14.0.6 h4fb70ea_0
    - expat 2.7.1 h313beb8_0
    - ld64_osx-arm64 530 hac4b543_26
    - ldid 2.1.5 h20b2a84_3
    - libclang-cpp14 14.0.6 default_h1b80db6_2
    - libcurl 8.14.1 hcdd2897_1
    - libcxx 14.0.6 h848a8c0_0
    - libev 4.33 h1a28f6b_1
    - libffi 3.4.4 hca03da5_1
    - libllvm14 14.0.6 h19fdd8a_4
    - libnghttp2 1.57.0 h62f6fdd_0
    - libssh2 1.11.1 h3e2b118_0
    - libuv 1.48.0 h80987f9_0
    - llvm-tools 14.0.6 h7ec7a93_4
    - lz4-c 1.9.4 h313beb8_1
    - macosx_deployment_target_osx-arm64 11.1 had524d6_1
    - ncurses 6.5 hee39554_0
    - ninja-base 1.12.1 h48ca7d4_0
    - openssl 3.0.17 h4ee41c1_0
    - rhash 1.4.3 h02f6b3c_0
    - tapi 1100.0.11 h8754e6a_1
    - xz 5.6.4 h80987f9_1
    - zlib 1.2.13 h18a0788_1
    - zstd 1.5.6 hfb09047_0
  host:
    - libcxx 17.0.6 he5c5206_4
  run:
    - __osx >=11.1
    - libcxx >=14.0.6
test:
  commands:
    - test -d ${PREFIX}/include/fmt
    - test -f ${PREFIX}/include/fmt/core.h
    - test -f ${PREFIX}/include/fmt/format.h
    - test -f ${PREFIX}/lib/cmake/fmt/fmt-config.cmake
    - test -f ${PREFIX}/lib/libfmt.dylib
about:
  description: '{fmt} is an open-source formatting library for C++.

    It can be used as a safe and fast alternative to (s)printf and iostreams.

    '
  dev_url: https://github.com/fmtlib/fmt
  doc_url: https://fmt.dev/latest/
  home: https://fmt.dev/latest/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: '{fmt} is an open-source formatting library for C++'
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 047e7f21-23b0-4130-870b-ff5e370c1d85
  recipe-maintainers:
    - saraedum
    - tdegeus
    - vitaut
  remote_url: git@github.com:AnacondaRecipes/fmt-feedstock.git
  sha: ceadd42ef69ddf5d1934eb9a0bd90aeb330fcaa9
